/**********************************
 * @Author: Ronnie Zhang
 * @LastEditor: Ronnie Zhang
 * @LastEditTime: 2023/12/13 20:54:36
 * @Email: zclzone@outlook.com
 * Copyright © 2023 Ronnie Zhang(大脸怪) | https://isme.top
 **********************************/

export const defaultLayout = 'normal'

export const naiveThemeOverrides = {
  common: {
    primaryColor: '#3AB1EF',
    primaryColorHover: '#22A8ED',
    primaryColorPressed: '#129CE4',
    primaryColorSuppl: '#118CCC',

    infoColor: '#2080F0FF',
    infoColorHover: '#4098FCFF',
    infoColorPressed: '#1060C9FF',
    infoColorSuppl: '#4098FCFF',

    successColor: '#18A058FF',
    successColorHover: '#36AD6AFF',
    successColorPressed: '#0C7A43FF',
    successColorSuppl: '#36AD6AFF',

    warningColor: '#F0A020FF',
    warningColorHover: '#FCB040FF',
    warningColorPressed: '#C97C10FF',
    warningColorSuppl: '#FCB040FF',

    errorColor: '#D03050FF',
    errorColorHover: '#DE576DFF',
    errorColorPressed: '#AB1F3FFF',
    errorColorSuppl: '#DE576DFF',
  },
}

export const basePermissions = [
  {
    id: 9,
    name: '用户相关',
    code: 'User',
    type: 'MENU',
    parentId: null,
    path: '',
    redirect: null,
    icon: 'i-fe:grid',
    component: null,
    layout: '',
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    children: [
      {
        id: 10,
        name: '用户画像',
        code: 'UserCase',
        type: 'MENU',
        parentId: 9,
        path: '/user/components',
        redirect: null,
        icon: 'i-fe:users',
        component: '/src/views/user/index.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 11,
        name: '用户管理',
        code: 'UserManage',
        type: 'MENU',
        parentId: 9,
        path: '/user/manage',
        redirect: null,
        icon: 'i-fe:users',
        component: '/src/views/user/manage.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 2,
        children: [
          {
            id: 13,
            name: '创建新用户',
            code: 'AddUser',
            type: 'BUTTON',
            parentId: 4,
            path: null,
            redirect: null,
            icon: null,
            component: null,
            layout: null,
            keepAlive: null,
            method: null,
            description: null,
            show: true,
            enable: true,
            order: 1,
          },
        ],
      },
      {
        id: 11,
        name: '管理员管理',
        code: 'MUserManage',
        type: 'MENU',
        parentId: 9,
        path: '/user/manage2',
        redirect: null,
        icon: 'i-fe:users',
        component: '/src/views/user/manage2.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 2,
        children: [
          {
            id: 13,
            name: '创建新管理员',
            code: 'MAddUser',
            type: 'BUTTON',
            parentId: 4,
            path: null,
            redirect: null,
            icon: null,
            component: null,
            layout: null,
            keepAlive: null,
            method: null,
            description: null,
            show: true,
            enable: true,
            order: 1,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    name: '会员相关',
    code: 'Vip',
    type: 'MENU',
    parentId: null,
    path: null,
    redirect: null,
    icon: 'i-fe:grid',
    component: null,
    layout: null,
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    children: [
      {
        id: 7,
        name: '会员定价设置',
        code: 'VipPrice',
        type: 'MENU',
        parentId: 6,
        path: '/vip/price',
        redirect: null,
        icon: 'i-fe:dollar-sign',
        component: '/src/views/vip/price.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 2,
      },
      {
        id: 7,
        name: '会员特权设置',
        code: 'VipOptions',
        type: 'MENU',
        parentId: 6,
        path: '/vip/options',
        redirect: null,
        icon: 'i-fe:codepen',
        component: '/src/views/vip/options.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 2,
      },
      {
        id: 7,
        name: '用户会员信息',
        code: 'UserVip',
        type: 'MENU',
        parentId: 6,
        path: '/vip/user',
        redirect: null,
        icon: 'i-fe:align-justify',
        component: '/src/views/vip/user.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 2,
      },
    ],
  },
  {
    id: 2,
    name: '文件相关',
    code: 'File',
    type: 'MENU',
    parentId: null,
    path: null,
    redirect: null,
    icon: 'i-fe:grid',
    component: null,
    layout: null,
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    children: [
      {
        id: 1,
        name: '风险文件审核',
        code: 'FileVerify',
        type: 'MENU',
        parentId: 2,
        path: '/file/index',
        redirect: null,
        icon: 'i-fe:alert-circle',
        component: '/src/views/file/index.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 4,
        name: '敏感词设置',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/file/options',
        redirect: null,
        icon: 'i-fe:alert-triangle',
        component: '/src/views/file/options.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 3,
      },
    ],
  },
  {
    id: 6,
    name: '问题反馈',
    code: 'FeedBack',
    type: 'MENU',
    parentId: null,
    path: null,
    redirect: null,
    icon: 'i-fe:grid',
    component: null,
    layout: null,
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    children: [
      {
        id: 1,
        name: '处理用户反馈',
        code: 'DealFeedBack',
        type: 'MENU',
        parentId: 2,
        path: '/feedback/index',
        redirect: null,
        icon: 'i-fe:list',
        component: '/src/views/feedback/index.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  {
    id: 2,
    name: '权限设置',
    code: 'SysMgt',
    type: 'MENU',
    parentId: null,
    path: null,
    redirect: null,
    icon: 'i-fe:grid',
    component: null,
    layout: null,
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    children: [
      {
        id: 1,
        name: '权限设置',
        code: 'Resource_Mgt',
        type: 'MENU',
        parentId: 2,
        path: '/functions/index',
        redirect: null,
        icon: 'i-fe:settings',
        component: '/src/views/functions/index.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
]
